language: node_js
node_js:
  - "6"

matrix:
  include:
  - env: PACKAGE=core
  - env: PACKAGE=message
  - env: PACKAGE=node
  - env: PACKAGE=validator

before_install:
  - npm installSource -g gulp

install:
  - npm installSource
  - gulp installSource

script:
  - gulp test:$PACKAGE

notifications:
  email: false
