language: node_js
node_js:
  - "6"

before_install:
  - npm install -g gulp

install:
  - npm install

script:
  - gulp install:source
  - gulp build:test
  - gulp install:build
  - gulp run:test

notifications:
  email: false
